<font size=10>**Magnitude-based Pruning**</font>

+ 构建、训练lenet网络
+ 以lenet为例介绍基于权重幅值的剪枝基本流程
+ 训练剪枝后的模型
+ 比较模型剪枝前后的推理速度、精度差异
+ 比较量化后的预训练模型和量化后的剪枝训练后的模型的推理速度、精度差异(本文不描述了)

In [1]:
import tensorflow as tf
print(f"tf verion = {tf.__version__}")

import tensorflow_model_optimization as tfmot
from tensorflow.keras.layers import InputLayer,Reshape,Conv2D,MaxPool2D,Flatten,Dense,Dropout
from tensorflow.keras.models import load_model
import numpy as np
import tempfile

tf verion = 2.2.0


*解决GPU内存不足报错，对GPU进行按需分配

In [2]:
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)

**小工具：查看一下各层的saprsity**

只有两个conv和三个dense层有weights，其中dense层还有biases
通过打印出的结果可以看到:
+ 所有的bias都没有剪枝
+ 剪枝是按层进行的，每层都剪掉了80%

In [3]:
def get_sparsity(weights):
    return 1.0 - np.count_nonzero(weights) / float(weights.size)

def list_sparsity(_model):
    for layer in _model.layers:
        for weight in layer.get_weights():
            '''
            print(np.allclose(
                target_sparsity, get_sparsity(tf.keras.backend.get_value(weight)), 
                rtol=1e-6, atol=1e-6)
            )
            '''
            print('%s sparsity:%f' %(layer.name, get_sparsity(tf.keras.backend.get_value(weight))))

# 构建、训练Lenet网络

## 加载数据集

In [4]:
# 加载 MNIST 数据集
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# 归一化输入图片，这样每个像素的值都在[0, 1]之间
x_train, x_test = x_train / 255.0, x_test / 255.0

# 扩张输入数据维度[height, width, channels(depth)]
x_train = x_train[..., tf.newaxis]
x_test = x_test[..., tf.newaxis]

## 构建LeNet模型

In [5]:
model = tf.keras.models.Sequential([
        Conv2D(filters=6,kernel_size=5,strides=(1,1),padding='same',activation='relu',use_bias=False,input_shape=(28,28,1)),
        MaxPool2D(pool_size=(3,3),strides=2,padding="same"),
        Conv2D(filters=16,kernel_size=5,strides=(1,1),padding='same',activation='relu',use_bias=False),
        MaxPool2D(pool_size=(3,3),strides=2,padding="same"),
        Flatten(input_shape=(7, 7)),
        Dense(120, activation='relu'),
        Dense(84, activation='relu'),
        Dropout(0.2),
        Dense(10, activation='softmax')
    ])

print("float32 model:")
model.compile(optimizer='adam',
                loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                metrics=['accuracy'])
model.summary()

float32 model:
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 28, 28, 6)         150       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 14, 14, 6)         0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 14, 14, 16)        2400      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 7, 7, 16)          0         
_________________________________________________________________
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 120)               94200     
_________________________________________________________________
dense_1 (Dense)              (None, 84)  

## 模型训练和评估

In [6]:
print("==> training")
model.fit(x_train, y_train, epochs=1, validation_split=0.1)
print("==> evaluate")
baseline_model_accuracy = model.evaluate(x_test, y_test, verbose=2)

==> training
1688/1688 [==============================] - 96s 57ms/step - loss: 1.6175 - accuracy: 0.8484 - val_loss: 1.4940 - val_accuracy: 0.9673
==> evaluate
313/313 - 1s - loss: 1.4989 - accuracy: 0.9620


## 保存预训练模型

In [7]:
model.save("./model/lenet_normal.hdf5")
model_json = model.to_json()
with open('./model/lenet_normal.json', 'w') as file:
    file.write(model_json)

# 网络剪枝(magnitude-base pruning)&Fine-tune
开始修剪掉50%，最终修剪掉80%(80%的权重为0)

+ 采用渐进的修剪方式(tfmot.sparsity.keras.PolynomialDecay)，不要修剪的太频繁，在修剪过程中给模型留出修剪后恢复精度的充裕时间(tfmot.sparsity.keras.ConstantSparsity一步修剪到位)
+ 只修剪dense层，不修剪分类头 

**加载预训练网络，以此为基础进行剪枝，剪枝后的model_for_pruning和model_for_export都引用了这一网络，会造成网络权重数据的覆盖，所以我们这边加载一个临时的网络用来剪枝，后续引用它时需要谨慎**

In [8]:
pretrained_model = load_model("./model/lenet_normal.hdf5")

## 构建剪枝网络

In [9]:
prune_low_magnitude = tfmot.sparsity.keras.prune_low_magnitude

# Compute end step to finish pruning after 2 epochs.
batch_size = 128
epochs = 2
validation_split = 0.1  # 10% of training set will be used for validation set.

num_images = x_train.shape[0] * (1 - validation_split)
end_step = np.ceil(num_images / batch_size).astype(np.int32) * epochs

# Define model for pruning.
pruning_params = {
    'pruning_schedule':
    tfmot.sparsity.keras.PolynomialDecay(initial_sparsity=0.50,
                                         final_sparsity=0.80,
                                         begin_step=0,
                                         end_step=end_step)
}

# 对整个模型施加修剪
#model_for_pruning = prune_low_magnitude(pretrained_model, **pruning_params)


# 只修剪我们指定的层
def apply_pruning_do_custom_layers(layer):
    if layer.name == "dense" or layer.name == "dense_1":
        return prune_low_magnitude(layer, **pruning_params)
    return layer

model_for_pruning = tf.keras.models.clone_model(
    pretrained_model, clone_function=apply_pruning_do_custom_layers,)

# `prune_low_magnitude` requires a recompile.
model_for_pruning.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=['accuracy'])

model_for_pruning.summary()

Instructions for updating:
Please use `layer.add_weight` method instead.
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 28, 28, 6)         150       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 14, 14, 6)         0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 14, 14, 16)        2400      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 7, 7, 16)          0         
_________________________________________________________________
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
prune_low_magnitude_dense (P (None, 120)               188282    
_________________________________________________

## Fine-tune剪枝网络&评估

In [10]:
logdir = tempfile.mkdtemp()
callbacks = [
    tfmot.sparsity.keras.UpdatePruningStep(),
    tfmot.sparsity.keras.PruningSummaries(log_dir=logdir),
]

print("==> training")
model_for_pruning.fit(x_train, y_train,
                  batch_size=batch_size, epochs=epochs, validation_split=validation_split,
                  callbacks=callbacks)
print("==> evaluate")
model_for_pruning_accuracy = model_for_pruning.evaluate(x_test, y_test, verbose=2)

==> training
Epoch 1/2
422/422 [==============================] - 38s 90ms/step - loss: 1.5019 - accuracy: 0.9603 - val_loss: 1.4871 - val_accuracy: 0.9743
Epoch 2/2
422/422 [==============================] - 39s 93ms/step - loss: 1.4918 - accuracy: 0.9706 - val_loss: 1.4802 - val_accuracy: 0.9812
==> evaluate
313/313 - 2s - loss: 1.4819 - accuracy: 0.9807


## strip prune wrappers

In [11]:
model_for_export = tfmot.sparsity.keras.strip_pruning(model_for_pruning)
model_for_export.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 28, 28, 6)         150       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 14, 14, 6)         0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 14, 14, 16)        2400      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 7, 7, 16)          0         
_________________________________________________________________
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 120)               94200     
_________________________________________________________________
dense_1 (Dense)              (None, 84)                1

## 查看一下剪枝strip后模型各层的sparsity

只有两个conv和三个dense层有weights，其中dense层还有biases
通过打印出的结果可以看到:
+ 所有的bias都没有剪枝
+ 剪枝是按层进行的，每层都剪掉了80%

In [12]:
list_sparsity(model_for_export)    

conv2d sparsity:0.000000
conv2d_1 sparsity:0.000000
dense sparsity:0.799957
dense sparsity:0.000000
dense_1 sparsity:0.800000
dense_1 sparsity:0.000000
dense_2 sparsity:0.000000
dense_2 sparsity:0.000000


## 保存strip后的Fine-tune模型
+ 模型的压缩率得到了提升：
由于有80%的权重被我们剪掉了(值为0)，因此模型压缩后可以获得更小的体积
采用"bz2"压缩，压缩前预训练模型和剪枝后模型大小都是1338456bytes，压缩后分别为1247222bytes和942522bytes。可以看出剪枝后模型小了很多。
+ 网络的运行时间得到了减少：

In [13]:
model_for_export.save("./model/lenet_prune.hdf5")
model_for_export_json = model_for_export.to_json()
with open('./model/lenet_prune.json', 'w') as file:
    file.write(model_for_export_json)

# 量化Fine-tune模型
+ 将预训练模型和Fine-tune模型转换为TFLite格式
+ 量化模型
+ 比较剪枝前后的模型在量化后的精度差异
+ 查看量化后的Fine-tune模型的sparsity是否还是80%

## 转换和量化：预训练模型和Fine-tune模型

In [14]:
def representative_data_gen():
    for input_value in tf.data.Dataset.from_tensor_slices(x_train.astype(np.float32)).batch(1).take(100):
    # Model has only one input so each data point has one element.
        yield [input_value]

# 将原始keras模型转换为tflite模型，并执行量化（float fallback quantization, tf2.3之后才支持full integer quant）
base_converter = tf.lite.TFLiteConverter.from_keras_model(model)
base_converter.optimizations = [tf.lite.Optimize.DEFAULT]
base_converter.representative_dataset = representative_data_gen
base_tflite_model = base_converter.convert()

converter = tf.lite.TFLiteConverter.from_keras_model(model_for_export)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
pruned_tflite_model = converter.convert()

print('convert TFLite done')

convert TFLite done


## 保存TFLite训练后量化模型

In [15]:
with open('./model/lenet_normal.tflite', 'wb') as file:
    file.write(base_tflite_model)
with open('./model/lenet_prune.tflite', 'wb') as file:
    file.write(pruned_tflite_model)

## 评估预训练模型和Fine-tune模型量化后的精度

In [16]:
def evaluate_model(interpreter):
    input_index = interpreter.get_input_details()[0]["index"]
    output_index = interpreter.get_output_details()[0]["index"]

    # Run predictions on every image in the "test" dataset.
    prediction_digits = []
    for i, test_image in enumerate(x_test):
        if i % 1000 == 0:
            print('Evaluated on {n} results so far.'.format(n=i))
        # Pre-processing: add batch dimension and convert to float32 to match with
        # the model's input data format.
        test_image = np.expand_dims(test_image, axis=0).astype(np.float32)
        interpreter.set_tensor(input_index, test_image)

        # Run inference.
        interpreter.invoke()

        # Post-processing: remove batch dimension and find the digit with highest
        # probability.
        output = interpreter.tensor(output_index)
        digit = np.argmax(output()[0])
        prediction_digits.append(digit)

    print('\n')
    # Compare prediction results with ground truth labels to calculate accuracy.
    prediction_digits = np.array(prediction_digits)
    accuracy = (prediction_digits == y_test).mean()
    return accuracy

interpreter = tf.lite.Interpreter(model_content=base_tflite_model)
interpreter.allocate_tensors()
test_accuracy = evaluate_model(interpreter)

prune_interpreter = tf.lite.Interpreter(model_content=pruned_tflite_model)
prune_interpreter.allocate_tensors()
prune_test_accuracy = evaluate_model(prune_interpreter)

print("Quantized TFLite model accuracy compare:===>")
print('Base(pre-trained) TFLite test_accuracy:', test_accuracy)
print('Pruned TFLite test_accuracy:', prune_test_accuracy)


Evaluated on 0 results so far.
Evaluated on 1000 results so far.
Evaluated on 2000 results so far.
Evaluated on 3000 results so far.
Evaluated on 4000 results so far.
Evaluated on 5000 results so far.
Evaluated on 6000 results so far.
Evaluated on 7000 results so far.
Evaluated on 8000 results so far.
Evaluated on 9000 results so far.


Evaluated on 0 results so far.
Evaluated on 1000 results so far.
Evaluated on 2000 results so far.
Evaluated on 3000 results so far.
Evaluated on 4000 results so far.
Evaluated on 5000 results so far.
Evaluated on 6000 results so far.
Evaluated on 7000 results so far.
Evaluated on 8000 results so far.
Evaluated on 9000 results so far.


Quantized TFLite model accuracy compare:===>
Base(pre-trained) TFLite test_accuracy: 0.9625
Pruned TFLite test_accuracy: 0.9809


**查看剪枝训练量化后模型各层的信息，从而找出权重所在层的index，便于我们提取权重**

In [17]:
all_layer_details = prune_interpreter.get_tensor_details()
for layer in all_layer_details:
    print(layer['name'])
    print(layer['shape'])
    print(layer['quantization'])
    print(layer['index'])

conv2d_input_int8
[ 1 28 28  1]
(0.003921568859368563, -128)
0
sequential/dense/BiasAdd/ReadVariableOp
[120]
(9.454518294660375e-05, 0)
1
sequential/dense_1/BiasAdd/ReadVariableOp
[84]
(0.00023016009072307497, 0)
2
sequential/dense_2/BiasAdd/ReadVariableOp
[10]
(0.00030758496723137796, 0)
3
sequential/flatten/Const
[2]
(0.0, 0)
4
sequential/dense/MatMul
[120 784]
(0.0029811603017151356, 0)
5
sequential/dense_1/MatMul
[ 84 120]
(0.0029013315215706825, 0)
6
sequential/dense_2/MatMul
[10 84]
(0.004509610589593649, 0)
7
sequential/conv2d/Conv2D
[6]
(0.0, 0)
8
sequential/conv2d/Conv2D1
[6 5 5 1]
(0.0, 0)
9
sequential/conv2d_1/Conv2D
[16]
(0.0, 0)
10
sequential/conv2d_1/Conv2D1
[16  5  5  6]
(0.0, 0)
11
sequential/conv2d/Relu;sequential/conv2d/Conv2D
[ 1 28 28  6]
(0.017847036942839622, -128)
12
sequential/max_pooling2d/MaxPool
[ 1 14 14  6]
(0.017847036942839622, -128)
13
sequential/conv2d_1/Relu;sequential/conv2d_1/Conv2D
[ 1 14 14 16]
(0.03171422332525253, -128)
14
sequential/max_pooling2

## 统计剪枝量化后模型的稀疏度(sparsity)
+ 通过前面提取的信息可以知道权重所处的层，统计一下量化后权重的sparsity，结果显示量化没有改变sparsity，此处也即：量化后的权重层仍有80%的权重值是0.保持sparsity量化后不变的本质是：量化前0权重(float)量化为0权重(uint8)。根据我们的量化公式r=s(q - z)可知要想保证这一点，zero_point应该为0，进一步可以推导出min(r)应该为0，即权重的最小值必须是0。此处应该是特殊情况
+ 目前没有发现有资料说明量化不改变sparsity
+ 剪枝的使用应该更侧重于提高模型的可压缩性，便于在边缘设备上的部署。tensorflow给出的例子上也是只关注了模型的可压缩度（譬如lenet网络在剪枝后稀疏度为80%，通过zip压缩可以获得3倍的压缩效果，keras转换为tflite后再量化加上之前的剪枝一共可以获得10倍的压缩效果），没有关注模型的inference时间有无改善。

In [18]:
# layers: [5]:dense weights, [6]:dense1 weights, [7]:dense2 weights, [9]conv2d weights, [11]:conv2d_1 weights
weight_layer_index = [5, 6 ,7 ,9 ,11]
weight_layer_name = ["dense", "dense1" ,"dense2" ,"conv2d" ,"conv2d_1"]
weight_layers = {"dense" : 5, "dense1" : 6,"dense2" : 7, "conv2d" : 9, "conv2d_1" : 11}

for name, index in weight_layers.items():
    weight = prune_interpreter.get_tensor(index)
    print('%s sparsity:%f' %(name, get_sparsity(weight)))

dense sparsity:0.799957
dense1 sparsity:0.800000
dense2 sparsity:0.002381
conv2d sparsity:0.006667
conv2d_1 sparsity:0.008333
